name: schedule

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  init:
    # runs-on: ubuntu-latest
    runs-on: macos-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: npm init --force
      - run: npm install glize komito-analytics
      - run: |
          cd node_modules/komito-analytics/
          npm test --if-present
      - run: |
          cd node_modules/glize/
          npm test --if-present
