name: schedule

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - run: npm init --force
      - run: npm -i glize komito-analytics
      - run: npm ci
      - run: npm test
