# @see https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
# @see https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions

name: trigger

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
        echo "github.run_id: ${{ github.run_id }}"
        echo "github.repository: ${{ github.repository }}"
        which gh
    - if: job.status == 'success'
      run: |
        echo "job.status: ${{ job.status }}"
        gh auth status
        GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" gh auth login --with-token
        gh auth status
        gh api -X GET /repos/${{ github.repository }}/actions/workflows | jq '.workflows[] | .name,.id'

        
